# Site settings
title: Musings and Perusings 
subtitle: "Blog of Francis Nguyen"
email: fm.nguyen937@gmail.com
description: "Welcome! Francis here. I'm a concert-chasing, coffee-obsessed, life-loving person just trying to make cool things and revolutionize education. Always down and trying to explore, adventure and experience. Senior | Informatics 2015 | UW | UX/UI/Industrial Design | Web Development"
baseurl: ""
url: "http://yourdomain.com"
github_username:  "fmnguyen"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed